# Generated by Django 5.1.2 on 2024-11-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('tanks_destroyed', models.IntegerField()),
                ('seconds_survived', models.IntegerField()),
                ('missiles_fired', models.IntegerField()),
            ],
        ),
    ]
